class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start2'
        self.MirrorCommand = 'mirror2'
        self.UnzipMirrorCommand = 'unzip2'
        self.TarMirrorCommand = 'tar2'
        self.CancelMirror = 'cancel2'
        self.CancelAllCommand = 'cnlall2'
        self.ListCommand = 'list2'
        self.StatusCommand = 'status2'
        self.AuthorizedUsersCommand = 'user2'
        self.AuthorizeCommand = 'auth'
        self.UnAuthorizeCommand = 'unauth'
        self.AddSudoCommand = 'addsudo2'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping2'
        self.RestartCommand = 'restart2'
        self.StatsCommand = 'stat2'
        self.HelpCommand = 'hlp2'
        self.LogCommand = 'log2'
        self.SpeedCommand = 'test2'
        self.CloneCommand = 'clone2'
        self.CountCommand = 'count2'
        self.WatchCommand = 'watch2'
        self.TarWatchCommand = 'tarwatch'
        self.DeleteCommand = 'del2'
        self.UsageCommand = 'usage2'
        self.MediaInfoCommand = 'mediainfo2'
        self.ConfigMenuCommand = 'config2'
        self.ShellCommand = 'shell2'
        self.UpdateCommand = 'update2'

BotCommands = _BotCommands()
